#!/bin/sh
# $Id: newnet,v 1.1.1.1.2.24 2009/04/13 11:03:55 syzop Exp $
	echo "|=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= "
	echo "|      UnrealIRCd Network Submission             "
	echo "|                                                "
	echo "| If you want your networks network file in the  "
	echo "| next release please attach your network file   "
	echo "| to an email and mail it to                     "
	echo "|  unreal-networks@lists.sourceforge.net         "
	echo "|                                                "
	echo "|=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-= "
	exit 1
